### DISCUSSION TITLE
Reolink RLC-810A IPC_523128M8MP v3.1.0.1162_22072805

### DISCUSSION THREAD

**Discussion by mrplow** [AT0myks/reolink-fw-archive#4] [Firmware sharing]
Reolink support sent me this updated firmware for my RLC-810A after complaining there were artifacts in the RTSP stream.

https://support.reolink.com/attachments/token/bKSdFp6o2FVWqOb0PvEejh7l2/?name=IPC_523128M8MP.1162_22072805.RLC-810A.IMX415.8MP.REOLINK.pak

md5sum: ad04f9c305e8b6539e37c545983280fb

I'm not sure if that link expires, so I uploaded it here
https://drive.google.com/file/d/1gi3QD_IVE_C9_HJ6MSZ9krKw83BS-hJZ/

**Comment by AT0myks** [comment]
Thanks, it's been added. I assume it fixed your issue?

I have yet to see a dead link from Reolink, so for now I only added the "official" one.

**Comment by mrplow** [comment]
I _think_ it fixed the issue. I haven't seen any video artifacts, but it's only been a few days.

**Comment by ggasperino** [comment]
@mrplow could you share your complete Frigate yaml config for your 810A or any links to other pertinent info. I'm a Frigate newb and have spent hours trying to get it right.

**Comment by mrplow** [comment]
@ggasperino 
You might have better luck in the frigate github discussion section, but here are my configs - I trimmed out my other cameras. Note that I'm using my nvidia card for detection and hw transcoding.

mosquitto docker-compose.yml
```yaml
version: '3'
services:

  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto:1.6
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=America/Vancouver
```

frigate docker-compose.yml
```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.0-tensorrt
    network_mode: host
#   (detect width * height * 1.5 * 9 + 270480)/1048576 = <shm size in mb>
    shm_size: "80mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/RAID/frigate:/media/frigate
      - /media/RAID/frigate/trt-models:/trt-models
      - ./config:/config
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
frigate config.conf
```yaml
mqtt:
  host: 192.168.1.10
  user: <redacted>
  password: <redacted>

ffmpeg:
  output_args:
    record: preset-record-generic-audio-copy

snapshots:
  enabled: True
  clean_copy: True
  timestamp: True
  bounding_box: True

go2rtc:
  streams:
    frontdoor: #Reolink RLC-810A - IPC_523128M8MP - v3.1.0.956_22041503
      - rtsp://<redacted>:<redacted>@192.168.1.150:554/h264Preview_01_main
      - ffmpeg:frontdoor#audio=opus

cameras:
  frontdoor:
    timestamp_style:
      position: "tl"
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 15
    objects:
      filters:
        car:
          mask:
            - 700,202,1097,720,1280,720,1280,0,700,0
        bird:
          mask:
            - 934,0,960,0,974,65,900,65
        person:
          min_area: 2000
          mask:
            - 934,0,960,0,974,65,900,65
            - 1280,316,1280,622,1158,504
        cat:
          mask:
            - 1280,316,1280,622,1158,504
    motion:
      mask:
        - 934,0,960,0,974,65,900,65
        - 1280,316,1280,622,1158,504

detectors:
  tensorrt:
    type: tensorrt
    device: 0

model:
  path: /trt-models/yolov7x-320.trt
  labelmap_path: /trt-models/coco_91cl.txt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
  model_type: yolox

record:
  enabled: True
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 14
      mode: active_objects
      objects:
        dog: 7
        cat: 7
        car: 7

objects:
  track:
    - bear
    - bird
    - car
    - cat
    - dog
    - person

birdseye:
  enabled: True
  mode: continuous

timestamp_style:
  format: "%Y-%m-%d %H:%M:%S"
  effect: shadow
```
